### ISSUE TITLE
Add a fact, a place to eat or something special about a town

### ISSUE THREAD

**Issue by Kryze** [Kryze/RandomTown#39]
For each town, it will be cool to have a fact about the town, something special that appears in this town like a statue or a shop that is part of the town history.

An idea will be to add for each town something like this :

```
"facts": [
    { "name":"Statue of...", "desc": "It's a statue...." },
    { "name":"Coffee Place", "desc":"It's a place to eat if you visit..."}
]
```

**Comment by Shubham0812** [comment]
@Kryze  I want to add more cities into the list, can I do it?
