### ISSUE TITLE
Add position (X,Y) of previous towns and for future ones

### ISSUE THREAD

**Issue by Kryze** [Kryze/RandomTown#5]
An idea would be to add the position of the town so it can be easily pinned in apps like Google Maps

**Comment by Rye-Guy** [comment]
Would you like this do be done automatically with data currently in the json file, or simply adding long and lat as coordinates on each town object?

**Comment by Kryze** [comment]
Since this project is only a JSON file for the moment, I think that adding them by hand is the only solution for the moment right ? :)

**Comment by Rye-Guy** [comment]
The long we wait the long it will take :P I will try and start the trend!

**Comment by Kryze** [comment]
I've merge your PR and added empty coordinates for users to fill ! :)

**Comment by Rye-Guy** [comment]
I think if people follow this pattern moving forward. Pull request #27 will effectively close this ticket.

**Comment by Kryze** [comment]
People seems to add the coordinates by themselves ! Nice work  @Rye-Guy ! I close this issue !
