### ISSUE TITLE
Add the Wikipedia page of each towns if it exist

### ISSUE THREAD

**Issue by Kryze** [Kryze/RandomTown#6]
If a person want more informations of a town, a good thing would be the possibility to have a link to the wikipedia page (if it exist)

**Comment by Voovs** [comment]
I'll look into it

**Comment by Kryze** [comment]
> 
> 
> I'll look into it

Have fun ! :)

**Comment by Voovs** [comment]
Is there any particular reason for choosing a json object instead of a standard js object?

**Comment by Kryze** [comment]
I'm used to JSON for data formatting that's all !
